### ISSUE TITLE
BDHero GUI v0.9.0.5: System.UnauthorizedAccessException: Access to the path '[redacted]' is denied.

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#22]
BDHero GUI v0.9.0.5 portable (built on 2014-04-04 22:58:03Z)
## Stack Trace

```
System.UnauthorizedAccessException: Access to the path '[redacted]' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at BDInfo.BDROM.GetDirectorySize(DirectoryInfo directoryInfo)
   at BDInfo.BDROM.GetDirectorySize(DirectoryInfo directoryInfo)
   at BDInfo.BDROM..ctor(String path)
   at BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   at BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   at BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: mscorlib
```
## Log Events

```
2014-04-05 16:12:05,704 [ 1] INFO  BDHero.Startup.LogInitializer - bdhero-gui v0.9.0.5 starting up
2014-04-05 16:12:05,751 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Checking if current process belongs to a Job Object...
2014-04-05 16:12:05,766 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Current process does not belong to a Job Object.
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - IsPortable        = True
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - RootDir           = [redacted]
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - InstallDir        = .
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - AppConfigDir      = \Config\Application
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - PluginConfigDir   = \Config\Plugins
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - RequiredPluginDir = \Plugins\Required
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - CustomPluginDir   = \Plugins\Custom
2014-04-05 16:12:07,841 [ 1] INFO  BDHero.Startup.LogInitializer - LogDir            = \Logs
2014-04-05 16:12:07,919 [ 1] INFO  log4net.ILog - Loaded 7 plugins:
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -     Disc Readers (1):
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -         BDInfo Disc Reader v0.5.8.2 (ad2a515b-4fce-4755-b206-65b178847e7d)
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -     Metadata Providers (3):
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -         ISAN Metadata Provider v0.9.0.5 (7e5acd92-c2dc-4503-a89f-8118feb8e796)
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -         TMDb v0.9.0.5 (5fbb0ac7-f2d8-4955-96eb-d820fa358c9a)
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -         ChapterDb v0.9.0.5 (5fce5c74-0498-4d8b-9aba-5ee6235ff469)
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -     Auto Detectors (1):
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -         BDHero Detective v0.9.0.5 (bda75b82-ab37-48b4-b830-1245399daa53)
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -     Name Providers (1):
2014-04-05 16:12:07,935 [ 1] INFO  log4net.ILog -         BDHero File Namer v0.9.0.5 (7841090c-8dae-4c54-87f8-958cbc6f8b0e)
2014-04-05 16:12:07,950 [ 1] INFO  log4net.ILog -     Muxers (1):
2014-04-05 16:12:07,950 [ 1] INFO  log4net.ILog -         FFmpeg v2.1.0.1 (beb49a31-0047-46cc-afce-455d026bb0cf)
2014-04-05 16:12:07,950 [ 1] INFO  log4net.ILog -     Post Processors (0)
2014-04-05 16:12:07,997 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Scanning for discs...
2014-04-05 16:12:08,340 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Found 0 discs
2014-04-05 16:12:23,582 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Scanning for discs...
2014-04-05 16:12:23,691 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Found 0 discs
2014-04-05 16:17:35,559 [ 1] DEBUG log4net.ILog - BDInfo Disc Reader is Running - 0,00% complete -  - 00:00:00 elapsed, 00:00:00 remaining
2014-04-05 16:17:35,787 [ 1] DEBUG log4net.ILog - BDInfo Disc Reader is Error - 0,00% complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-05 16:17:35,789 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
System.UnauthorizedAccessException: Access to the path '[redacted]' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at BDInfo.BDROM.GetDirectorySize(DirectoryInfo directoryInfo)
   at BDInfo.BDROM.GetDirectorySize(DirectoryInfo directoryInfo)
   at BDInfo.BDROM..ctor(String path)
   at BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   at BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   at BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()
2014-04-05 16:17:37,715 [ 1] DEBUG log4net.ILog - Scan failed!
2014-04-05 16:17:43,019 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Scanning for discs...
2014-04-05 16:17:43,128 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Found 1 discs
2014-04-05 16:17:45,374 [ 1] DEBUG log4net.ILog - BDInfo Disc Reader is Running - 0,00% complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-05 16:17:45,577 [ 1] DEBUG log4net.ILog - BDInfo Disc Reader is Error - 0,00% complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-05 16:17:45,577 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
System.UnauthorizedAccessException: Access to the path '[redacted]' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at BDInfo.BDROM.GetDirectorySize(DirectoryInfo directoryInfo)
   at BDInfo.BDROM.GetDirectorySize(DirectoryInfo directoryInfo)
   at BDInfo.BDROM..ctor(String path)
   at BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   at BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   at BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()
2014-04-05 16:17:47,305 [ 1] DEBUG log4net.ILog - Scan failed!
2014-04-05 16:18:01,766 [ 1] DEBUG log4net.ILog - BDInfo Disc Reader is Running - 0,00% complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-05 16:18:01,984 [ 1] DEBUG log4net.ILog - BDInfo Disc Reader is Error - 0,00% complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-05 16:18:01,984 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-04 22:57:57Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.5 | 2014-04-04 22:57:58Z |  |
| 1 | TMDb | 0.9.0.5 | 2014-04-04 22:57:57Z |  |
| 2 | ChapterDb | 0.9.0.5 | 2014-04-04 22:57:56Z |  |
| 0 | BDHero Detective | 0.9.0.5 | 2014-04-04 22:57:56Z |  |
| 0 | BDHero File Namer | 0.9.0.5 | 2014-04-04 22:57:57Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-04 22:57:58Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 8
    TotalPhysicalMemory: 8545017856 bytes (8,0 GiB)
    AvailableMemory: 6285512704 bytes (5,9 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: pl-PL
    CurrentCulture: pl-PL
    CurrentUICulture: pl-PL
```

**Comment by acdvorak** [comment]
Closed by commit efda3f9
