### ISSUE TITLE
BDHero GUI v0.9.0.6: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[ChapterGrabberPlugin.JsonChapter]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'chapterInfo.chapters.chapter.time', line 22, position 16.

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#28]
BDHero GUI v0.9.0.6 (built on 2014-04-08 09:06:16Z)
## Stack Trace

```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[ChapterGrabberPlugin.JsonChapter]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'chapterInfo.chapters.chapter.time', line 22, position 16.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ChapterGrabberPlugin.ChapterGrabberPlugin.GetChapters(String movieName)
   at ChapterGrabberPlugin.ChapterGrabberPlugin.GetMetadata(CancellationToken cancellationToken, Job job)
   at BDHero.Controller.<>c__DisplayClass30.<GetMetadata>b__2f(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: Newtonsoft.Json
```
## Log Events

```
2014-04-15 01:02:23,721 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:04 elapsed, 00:00:04 remaining
2014-04-15 01:02:23,971 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:05 elapsed, 00:00:05 remaining
2014-04-15 01:02:24,231 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:05 elapsed, 00:00:05 remaining
2014-04-15 01:02:24,501 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:05 elapsed, 00:00:05 remaining
2014-04-15 01:02:24,752 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:05 elapsed, 00:00:05 remaining
2014-04-15 01:02:25,012 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:06 elapsed, 00:00:06 remaining
2014-04-15 01:02:25,282 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:06 elapsed, 00:00:06 remaining
2014-04-15 01:02:25,532 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:06 elapsed, 00:00:06 remaining
2014-04-15 01:02:25,792 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:07 elapsed, 00:00:07 remaining
2014-04-15 01:02:26,062 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:07 elapsed, 00:00:07 remaining
2014-04-15 01:02:26,312 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:07 elapsed, 00:00:07 remaining
2014-04-15 01:02:26,572 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:07 elapsed, 00:00:07 remaining
2014-04-15 01:02:26,842 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:08 elapsed, 00:00:08 remaining
2014-04-15 01:02:27,092 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:08 elapsed, 00:00:08 remaining
2014-04-15 01:02:27,352 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:08 elapsed, 00:00:08 remaining
2014-04-15 01:02:27,622 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:08 elapsed, 00:00:08 remaining
2014-04-15 01:02:27,872 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:09 elapsed, 00:00:09 remaining
2014-04-15 01:02:28,132 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:09 elapsed, 00:00:09 remaining
2014-04-15 01:02:28,402 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:09 elapsed, 00:00:09 remaining
2014-04-15 01:02:28,652 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:09 elapsed, 00:00:09 remaining
2014-04-15 01:02:28,912 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:10 elapsed, 00:00:10 remaining
2014-04-15 01:02:29,182 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:10 elapsed, 00:00:10 remaining
2014-04-15 01:02:29,432 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:10 elapsed, 00:00:10 remaining
2014-04-15 01:02:29,692 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:10 elapsed, 00:00:10 remaining
2014-04-15 01:02:29,962 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:11 elapsed, 00:00:11 remaining
2014-04-15 01:02:30,212 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:11 elapsed, 00:00:11 remaining
2014-04-15 01:02:30,472 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:11 elapsed, 00:00:11 remaining
2014-04-15 01:02:30,742 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:11 elapsed, 00:00:11 remaining
2014-04-15 01:02:30,992 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:12 elapsed, 00:00:12 remaining
2014-04-15 01:02:31,252 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:12 elapsed, 00:00:12 remaining
2014-04-15 01:02:31,522 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:12 elapsed, 00:00:12 remaining
2014-04-15 01:02:31,772 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:12 elapsed, 00:00:12 remaining
2014-04-15 01:02:32,032 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:13 elapsed, 00:00:13 remaining
2014-04-15 01:02:32,302 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:13 elapsed, 00:00:13 remaining
2014-04-15 01:02:32,552 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:13 elapsed, 00:00:13 remaining
2014-04-15 01:02:32,812 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:14 elapsed, 00:00:14 remaining
2014-04-15 01:02:33,082 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:14 elapsed, 00:00:14 remaining
2014-04-15 01:02:33,332 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:14 elapsed, 00:00:14 remaining
2014-04-15 01:02:33,592 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:14 elapsed, 00:00:14 remaining
2014-04-15 01:02:33,853 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:15 elapsed, 00:00:15 remaining
2014-04-15 01:02:34,113 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:15 elapsed, 00:00:15 remaining
2014-04-15 01:02:34,373 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:15 elapsed, 00:00:15 remaining
2014-04-15 01:02:34,633 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 50.00 % complete - Getting poster images... - 00:00:15 elapsed, 00:00:15 remaining
2014-04-15 01:02:34,693 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Running - 100.00 % complete - Finished querying TMDb - 00:00:15 elapsed, 00:00:15 remaining
2014-04-15 01:02:34,713 [ 1] DEBUG BDHeroGUI.FormMain - TMDb is Success - 100.00 % complete - Finished querying TMDb - 00:00:15 elapsed, 00:00:00 remaining
2014-04-15 01:02:34,713 [ 1] DEBUG DotNetUtils.Net.HttpRequest - GET "http://chapterdb.org/chapters/search?title=Avatar&chapterCount=0 HTTP/1.1" -- cache = False with headers: ApiKey: G88IO875M9SKU6DPB82F; UserName: BDHero
2014-04-15 01:02:34,713 [ 1] DEBUG BDHeroGUI.FormMain - ChapterDb is Running - 0.00 % complete - Finished querying ChapterDb.org - 00:00:00 elapsed, 00:00:00 remaining
2014-04-15 01:02:34,973 [ 1] DEBUG BDHeroGUI.FormMain - ChapterDb is Running - 0.00 % complete - Querying ChapterDb.org... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-15 01:02:41,483 [ 1] DEBUG BDHeroGUI.FormMain - ChapterDb is Error - 0.00 % complete - Querying ChapterDb.org... - 00:00:06 elapsed, 00:00:00 remaining
2014-04-15 01:02:41,483 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-08 09:06:11Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.6 | 2014-04-08 09:06:11Z |  |
| 1 | TMDb | 0.9.0.6 | 2014-04-08 09:06:11Z |  |
| 2 | ChapterDb | 0.9.0.6 | 2014-04-08 09:06:11Z |  |
| 0 | BDHero Detective | 0.9.0.6 | 2014-04-08 09:06:11Z |  |
| 0 | BDHero File Namer | 0.9.0.6 | 2014-04-08 09:06:12Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-08 09:06:14Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 8
    TotalPhysicalMemory: 8588406784 bytes (8.0 GiB)
    AvailableMemory: 4594130944 bytes (4.3 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: en-US
    CurrentCulture: en-US
    CurrentUICulture: en-US
```

**Comment by acdvorak** [comment]
Fixed in v0.9.0.7
