### ISSUE TITLE
BDHero GUI v0.9.1.2: BDHero.Plugin.FFmpegMuxer.FFmpegException: [redacted]\_ Babette's Feast (1987) BD50 Bluray: Invalid argument

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#69]
BDHero GUI v0.9.1.2 (built on 2014-05-04 20:27:54Z)
## Stack Trace

```
BDHero.Plugin.FFmpegMuxer.FFmpegException: [redacted]\_ Babette's Feast (1987) BD50 Bluray: Invalid argument ---> BDHero.Plugin.FFmpegMuxer.FFmpegException: [redacted]\_ Babette's Feast (1987) BD50 Bluray: Invalid argument
   at BDHero.Plugin.FFmpegMuxer.FFmpeg.OnStdErr(String line) in [redacted]\FFmpeg.cs:line 282
   --- End of inner exception stack trace ---
   at BDHero.Plugin.FFmpegMuxer.FFmpegPlugin.Mux(CancellationToken cancellationToken, Job job) in [redacted]\FFmpegPlugin.cs:line 108
   at BDHero.Controller.<>c__DisplayClass45.<Mux>b__44(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: FFmpegMuxerPlugin
```
## Log Events

```
2014-10-22 18:35:51,866 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 96,36% complete - Scanning stream file 00166.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,875 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 96,80% complete - Scanning stream file 00166.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,877 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 96,80% complete - Scanning stream file 00165.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,917 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 97,24% complete - Scanning stream file 00165.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,919 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 97,24% complete - Scanning stream file 00161.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,957 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 97,68% complete - Scanning stream file 00161.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,958 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 97,68% complete - Scanning stream file 00163.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,996 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 98,12% complete - Scanning stream file 00163.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:51,997 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 98,12% complete - Scanning stream file 00162.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,024 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 98,56% complete - Scanning stream file 00162.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,026 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 98,56% complete - Scanning stream file 00135.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,032 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 98,56% complete - Scanning stream file 00135.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,124 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 99,00% complete - Scanning stream file 00135.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,130 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 99,00% complete - Transforming BDInfo structure into BDHero structure... - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,227 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 100,00% complete - Finished scanning BD-ROM - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,282 [ 1] DEBUG BDHero.Plugin.ProgressProvider - PercentComplete is already 100.00 %
2014-10-22 18:35:52,284 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Success - 100,00% complete - Finished scanning BD-ROM - 00:00:02 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,287 [ 1] DEBUG BDHeroGUI.FormMain - BDHero Detective is Running - 0,00% complete - Finished auto detecting - 00:00:00 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,293 [ 1] DEBUG BDHeroGUI.FormMain - BDHero Detective is Running - 0,00% complete - Gathering data... - 00:00:00 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,311 [ 1] DEBUG BDHeroGUI.FormMain - BDHero Detective is Running - 100,00% complete - Finished auto detecting - 00:00:00 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,394 [ 1] DEBUG BDHero.Plugin.ProgressProvider - PercentComplete is already 100.00 %
2014-10-22 18:35:52,396 [ 1] DEBUG BDHeroGUI.FormMain - BDHero Detective is Success - 100,00% complete - Finished auto detecting - 00:00:00 elapsed, 00:00:00 remaining
2014-10-22 18:35:52,397 [ 4] INFO  BDHero.Controller - 00800.MPLS: 01:37:28.0920000, 27085934592 bytes, 20 chapters, MainFeature
2014-10-22 18:35:52,404 [ 1] DEBUG BDHeroGUI.FormMain - Scan succeeded!
2014-10-22 18:35:56,748 [ 1] DEBUG BDHeroGUI.FormMain - Convert started...
2014-10-22 18:35:56,794 [13] INFO  BDHero.Controller - Muxing with FFmpeg
2014-10-22 18:35:56,796 [13] WARN  BDHero.JobQueue.Job - No release medium (movie or TV show) is selected
2014-10-22 18:35:56,799 [13] INFO  BDHero.BDROM.Playlist - 00800.MPLS: 01:37:28.092, 20 chapters, 27,085,934,592 bytes
    Track w/ stream PID  4113 (0x1011):  0 [X] eng, 1080p H.264/AVC @ 23.976 (16:9)
    Track w/ stream PID  4352 (0x1100):  1 [X] eng, DTS-HD Master 7,1 ch
    Track w/ stream PID  4353 (0x1101):  2 [ ] eng, Pro Logic 2,0 ch
    Track w/ stream PID  4354 (0x1102):  3 [ ] ita, DTS 5,1 ch
    Track w/ stream PID  4608 (0x1200):  4 [X] eng, PGS
    Track w/ stream PID  4609 (0x1201):  5 [ ] ita, PGS
    Track w/ stream PID  4610 (0x1202):  6 [ ] dan, PGS
    Track w/ stream PID  4611 (0x1203):  7 [ ] fin, PGS
    Track w/ stream PID  4612 (0x1204):  8 [ ] nor, PGS
    Track w/ stream PID  4613 (0x1205):  9 [ ] swe, PGS
2014-10-22 18:35:56,803 [11] INFO  BDHero.Plugin.FFmpegMuxer.FFmpegPlugin - Starting FFmpeg process...
2014-10-22 18:35:56,810 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 0,00% complete - Starting FFmpeg process... - 00:00:00 elapsed, 00:00:00 remaining
2014-10-22 18:35:56,823 [ 7] INFO  ProcessUtils.NonInteractiveProcess - [redacted]\ffmpeg.exe -report -loglevel error -progress [redacted]\progress.log -fflags +genpts -y -f concat -i [redacted]\inputFileList.txt -metadata title=Maleficent -map 0:0 -metadata:s:0 language=eng -metadata:s:0 "title=Main Feature: H.264 (1080p)" -map 0:1 -metadata:s:1 language=eng -metadata:s:1 "title=Main Feature: DTS-HD MA (7,1 ch)" -map 0:4 -metadata:s:2 language=eng -metadata:s:2 "title=Main Feature: PGS" -c copy "[redacted]\_ Babette's Feast (1987) BD50 Bluray"
2014-10-22 18:35:56,845 [ 7] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted]\ffmpeg.exe" changing state from Ready to Running
2014-10-22 18:35:56,870 [ 7] INFO  ProcessUtils.NonInteractiveProcess - Waiting for process "[redacted]\ffmpeg.exe" w/ PID = 2668 to exit...
2014-10-22 18:35:57,272 [12] ERROR BDHero.Plugin.FFmpegMuxer.FFmpeg - [NULL @ 049ea280] Unable to find a suitable output format for '[redacted]\_ Babette's Feast (1987) BD50 Bluray'
2014-10-22 18:35:57,274 [12] ERROR BDHero.Plugin.FFmpegMuxer.FFmpeg - [redacted]\_ Babette's Feast (1987) BD50 Bluray: Invalid argument
2014-10-22 18:35:57,373 [ 7] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted]\ffmpeg.exe" w/ PID = 2668 exited
2014-10-22 18:35:57,779 [ 9] WARN  ProcessUtils.NonInteractiveProcess - Process "[redacted]\ffmpeg.exe" exited uncleanly (asynchronous event)
2014-10-22 18:35:57,847 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-10-22 18:35:58,086 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 0,00% complete - Muxing to MKV: 00:00:00.000 - 0 B @ 0,0 fps - 00:00:01 elapsed, 00:00:00 remaining
2014-10-22 18:35:58,282 [ 7] WARN  ProcessUtils.NonInteractiveProcess - Process "[redacted]\ffmpeg.exe" exited uncleanly (synchronous event)
2014-10-22 18:35:58,284 [ 7] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted]\ffmpeg.exe" changing state from Running to Error
2014-10-22 18:35:58,285 [ 7] ERROR BDHero.Plugin.FFmpegMuxer.FFmpeg - FFmpeg exited with state Error and code 1
2014-10-22 18:35:58,287 [ 7] INFO  BDHero.Plugin.FFmpegMuxer.FFmpegPlugin - FFmpeg exited with state Error and code 1
2014-10-22 18:35:58,294 [11] INFO  BDHero.Plugin.FFmpegMuxer.FFmpegPlugin - FFmpeg was invoked with: [redacted]\ffmpeg.exe -report -loglevel error -progress [redacted]\progress.log -fflags +genpts -y -f concat -i [redacted]\inputFileList.txt -metadata title=Maleficent -map 0:0 -metadata:s:0 language=eng -metadata:s:0 "title=Main Feature: H.264 (1080p)" -map 0:1 -metadata:s:1 language=eng -metadata:s:1 "title=Main Feature: DTS-HD MA (7,1 ch)" -map 0:4 -metadata:s:2 language=eng -metadata:s:2 "title=Main Feature: PGS" -c copy "[redacted]\_ Babette's Feast (1987) BD50 Bluray"
2014-10-22 18:35:58,296 [11] WARN  BDHero.JobQueue.Job - No release medium (movie or TV show) is selected
2014-10-22 18:35:58,298 [11] INFO  BDHero.BDROM.Playlist - 00800.MPLS: 01:37:28.092, 20 chapters, 27,085,934,592 bytes
    Track w/ stream PID  4113 (0x1011):  0 [X] eng, 1080p H.264/AVC @ 23.976 (16:9)
    Track w/ stream PID  4352 (0x1100):  1 [X] eng, DTS-HD Master 7,1 ch
    Track w/ stream PID  4353 (0x1101):  2 [ ] eng, Pro Logic 2,0 ch
    Track w/ stream PID  4354 (0x1102):  3 [ ] ita, DTS 5,1 ch
    Track w/ stream PID  4608 (0x1200):  4 [X] eng, PGS
    Track w/ stream PID  4609 (0x1201):  5 [ ] ita, PGS
    Track w/ stream PID  4610 (0x1202):  6 [ ] dan, PGS
    Track w/ stream PID  4611 (0x1203):  7 [ ] fin, PGS
    Track w/ stream PID  4612 (0x1204):  8 [ ] nor, PGS
    Track w/ stream PID  4613 (0x1205):  9 [ ] swe, PGS
2014-10-22 18:35:58,300 [11] WARN  BDHero.Plugin.FFmpegMuxer.FFmpeg - StdErr:
    2014-10-22 18:35:57,272 [NULL @ 049ea280] Unable to find a suitable output format for '[redacted]\_ Babette's Feast (1987) BD50 Bluray'
    2014-10-22 18:35:57,274 [redacted]\_ Babette's Feast (1987) BD50 Bluray: Invalid argument
2014-10-22 18:35:58,336 [11] WARN  BDHero.Plugin.FFmpegMuxer.FFmpeg - Report Dump:
        Stream #0:0, 35, 1/90000: Video: h264 (High) (HDMV [redacted]\ 0x564D4448), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
        Stream #0:1, 76, 1/90000: Audio: dts (DTS-HD MA) ([134][0][0][0] [redacted]\s
        Stream #0:2, 33, 1/90000: Audio: ac3 (AC-3 [redacted]\s
        Stream #0:3, 76, 1/90000: Audio: dts (DTS) ([130][0][0][0] [redacted]\s
        Stream #0:4, 0, 1/90000: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] [redacted]\ 0x0090)
        Stream #0:5, 0, 1/90000: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] [redacted]\ 0x0090)
        Stream #0:6, 0, 1/90000: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] [redacted]\ 0x0090)
        Stream #0:7, 0, 1/90000: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] [redacted]\ 0x0090)
        Stream #0:8, 0, 1/90000: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] [redacted]\ 0x0090)
        Stream #0:9, 0, 1/90000: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] [redacted]\ 0x0090)
    Successfully opened the file.
    Parsing a group of options: output file [redacted]\_ Babette's Feast (1987) BD50 Bluray.
    Applying option metadata (add metadata) with argument title=Maleficent.
    Applying option map (set input stream mapping) with argument 0:0.
    Applying option metadata:s:0 (add metadata) with argument language=eng.
    Applying option metadata:s:0 (add metadata) with argument title=Main Feature: H.264 (1080p).
    Applying option map (set input stream mapping) with argument 0:1.
    Applying option metadata:s:1 (add metadata) with argument language=eng.
    Applying option metadata:s:1 (add metadata) with argument title=Main Feature: DTS-HD MA (7,1 ch).
    Applying option map (set input stream mapping) with argument 0:4.
    Applying option metadata:s:2 (add metadata) with argument language=eng.
    Applying option metadata:s:2 (add metadata) with argument title=Main Feature: PGS.
    Applying option c (codec name) with argument copy.
    Successfully parsed a group of options.
    Opening an output file: [redacted]\_ Babette's Feast (1987) BD50 Bluray.
    [NULL @ 049ea280] Unable to find a suitable output format for '[redacted]\_ Babette's Feast (1987) BD50 Bluray'
    [redacted]\_ Babette's Feast (1987) BD50 Bluray: Invalid argument
    [AVIOContext @ 018bbbc0] Statistics: 11358356 bytes read, 3 seeks
    [AVIOContext @ 018bb1a0] Statistics: 98 bytes read, 0 seeks
2014-10-22 18:35:58,444 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Error - 0,00% complete - Muxing to MKV: 00:00:00.000 - 0 B @ 0,0 fps - 00:00:01 elapsed, 00:00:00 remaining
2014-10-22 18:35:58,445 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-05-04 20:27:45Z |  |
| 0 | ISAN Metadata Provider | 0.9.1.2 | 2014-05-04 20:27:44Z | DIS |
| 1 | TMDb | 0.9.1.2 | 2014-05-04 20:27:45Z | DIS |
| 2 | ChapterDb | 0.9.1.2 | 2014-05-04 20:27:45Z | DIS |
| 0 | BDHero Detective | 0.9.1.2 | 2014-05-04 20:27:43Z |  |
| 0 | BDHero File Namer | 0.9.1.2 | 2014-05-04 20:27:47Z | DIS |
| 0 | FFmpeg | 2.1.4.0 | 2014-05-04 20:27:52Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7600.0
    VersionString: Microsoft Windows NT 6.1.7600.0
    Is64Bit: True
Hardware: 
    ProcessorCount: 6
    TotalPhysicalMemory: 17164361728 bytes (16,0 GiB)
    AvailableMemory: 14627971072 bytes (13,6 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: it-IT
    CurrentCulture: it-IT
    CurrentUICulture: it-IT
```

**Comment by herosphero** [comment]
Hi,
BDHero worked well yesterday, today... it makes me despair, help please.
Thanks in advance
