### ISSUE TITLE
BDHero GUI v0.9.1.2: BDHero.Plugin.DiscReader.Exceptions.PlaylistFileScanException: Error occurred while scanning playlist file 00053.MPLS

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#72]
BDHero GUI v0.9.1.2 (built on 2014-05-04 14:27:54Z)
## Stack Trace

```
BDHero.Plugin.DiscReader.Exceptions.PlaylistFileScanException: Error occurred while scanning playlist file 00053.MPLS ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at BDInfo.TSPlaylistFile.Scan(Dictionary`2 streamFiles, Dictionary`2 streamClipFiles) in [redacted]\TSPlaylistFile.cs:line 565
   at BDInfo.BDROM.Scan(CancellationToken cancellationToken) in [redacted]\BDROM.cs:line 352
   --- End of inner exception stack trace ---
   at BDHero.Plugin.DiscReader.DiscReader.BDROMOnPlaylistFileScanError(TSPlaylistFile playlistFile, Exception exception) in [redacted]\DiscReader.cs:line 122
   at BDInfo.BDROM.Scan(CancellationToken cancellationToken) in [redacted]\BDROM.cs:line 362
   at BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath) in [redacted]\DiscReader.cs:line 106
   at BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath) in [redacted]\DiscReader.cs:line 70
   at BDHero.Controller.<>c__DisplayClass2a.<ReadBDROM>b__27(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: DiscReaderPlugin
```
## Log Events

```
2015-01-02 18:37:12,838 [ 1] INFO  BDHero.Startup.LogInitializer - bdhero-gui v0.9.1.2 starting up
2015-01-02 18:37:12,885 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Checking if current process belongs to a Job Object...
2015-01-02 18:37:12,901 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Current process does not belong to a Job Object.
2015-01-02 18:37:14,776 [ 1] INFO  BDHero.Startup.LogInitializer - Directories:
    IsPortable        = False
    RootDir           = C:\Users\Chris\AppData\
    InstallDir        = Local\BDHero\Application
    AppConfigDir      = Roaming\BDHero\Config\Application
    PluginConfigDir   = Roaming\BDHero\Config\Plugins
    RequiredPluginDir = Local\BDHero\Application\Plugins
    CustomPluginDir   = Roaming\BDHero\Plugins
    LogDir            = Local\BDHero\Logs
2015-01-02 18:37:14,854 [ 1] INFO  BDHero.Startup.PluginLoader - Loaded 7 plugins:
    Disc Readers (1):
        BDInfo Disc Reader v0.5.8.2 (ad2a515b-4fce-4755-b206-65b178847e7d)
    Metadata Providers (3):
        ISAN Metadata Provider v0.9.1.2 (7e5acd92-c2dc-4503-a89f-8118feb8e796)
        TMDb v0.9.1.2 (5fbb0ac7-f2d8-4955-96eb-d820fa358c9a)
        ChapterDb v0.9.1.2 (5fce5c74-0498-4d8b-9aba-5ee6235ff469)
    Auto Detectors (1):
        BDHero Detective v0.9.1.2 (bda75b82-ab37-48b4-b830-1245399daa53)
    Name Providers (1):
        BDHero File Namer v0.9.1.2 (7841090c-8dae-4c54-87f8-958cbc6f8b0e)
    Muxers (1):
        FFmpeg v2.1.4.0 (beb49a31-0047-46cc-afce-455d026bb0cf)
    Post Processors (0)
2015-01-02 18:37:14,901 [ 1] INFO  BDHeroGUI.Components.DiscMenu - Scanning for discs...
2015-01-02 18:37:20,730 [ 1] INFO  BDHeroGUI.Components.DiscMenu - Found 0 discs
2015-01-02 18:37:40,029 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00% complete -  - 00:00:00 elapsed, 00:00:00 remaining
2015-01-02 18:37:40,138 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.32% complete - Scanning stream clip file 00001.CLPI - 00:00:00 elapsed, 00:00:00 remaining
2015-01-02 18:37:40,248 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 35.31% complete - Scanning playlist file 00053.MPLS - 00:00:00 elapsed, 00:00:00 remaining
2015-01-02 18:37:40,341 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 35.31% complete - Scanning playlist file 00053.MPLS - 00:00:00 elapsed, 00:00:00 remaining
2015-01-02 18:37:40,341 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-05-04 14:27:45Z |  |
| 0 | ISAN Metadata Provider | 0.9.1.2 | 2014-05-04 14:27:44Z |  |
| 1 | TMDb | 0.9.1.2 | 2014-05-04 14:27:45Z |  |
| 2 | ChapterDb | 0.9.1.2 | 2014-05-04 14:27:45Z |  |
| 0 | BDHero Detective | 0.9.1.2 | 2014-05-04 14:27:43Z |  |
| 0 | BDHero File Namer | 0.9.1.2 | 2014-05-04 14:27:47Z |  |
| 0 | FFmpeg | 2.1.4.0 | 2014-05-04 14:27:52Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.3.9600.0
    VersionString: Microsoft Windows NT 6.3.9600.0
    Is64Bit: True
Hardware: 
    ProcessorCount: 4
    TotalPhysicalMemory: 4294066176 bytes (4.0 GiB)
    AvailableMemory: 1850044416 bytes (1.7 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: en-GB
    CurrentCulture: en-GB
    CurrentUICulture: en-GB
```

**Comment by bdhero-issues** [comment]
BDHero GUI v0.9.1.2 portable (built on 2014-05-05 02:27:54Z)

## Stack Trace

```
BDHero.Plugin.DiscReader.Exceptions.PlaylistFileScanException: Error occurred while scanning playlist file 00001.MPLS ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at BDInfo.TSPlaylistFile.Scan(Dictionary`2 streamFiles, Dictionary`2 streamClipFiles) in [redacted]\TSPlaylistFile.cs:line 565
   at BDInfo.BDROM.Scan(CancellationToken cancellationToken) in [redacted]\BDROM.cs:line 352
   --- End of inner exception stack trace ---
   at BDHero.Plugin.DiscReader.DiscReader.BDROMOnPlaylistFileScanError(TSPlaylistFile playlistFile, Exception exception) in [redacted]\DiscReader.cs:line 122
   at BDInfo.BDROM.Scan(CancellationToken cancellationToken) in [redacted]\BDROM.cs:line 362
   at BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath) in [redacted]\DiscReader.cs:line 106
   at BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath) in [redacted]\DiscReader.cs:line 70
   at BDHero.Controller.<>c__DisplayClass2a.<ReadBDROM>b__27(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: DiscReaderPlugin
```

## Log Events

```
2015-01-06 16:50:57,515 [ 1] INFO  BDHero.Startup.LogInitializer - bdhero-gui v0.9.1.2 starting up
2015-01-06 16:50:57,577 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Checking if current process belongs to a Job Object...
2015-01-06 16:50:57,593 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Current process does not belong to a Job Object.
2015-01-06 16:50:59,667 [ 1] INFO  BDHero.Startup.LogInitializer - Directories:
    IsPortable        = True
    RootDir           = [redacted]\bdhero-0.9.1.2
    InstallDir        = .
    AppConfigDir      = \Config\Application
    PluginConfigDir   = \Config\Plugins
    RequiredPluginDir = \Plugins\Required
    CustomPluginDir   = \Plugins\Custom
    LogDir            = \Logs
2015-01-06 16:50:59,761 [ 1] INFO  BDHero.Startup.PluginLoader - Loaded 7 plugins:
    Disc Readers (1):
        BDInfo Disc Reader v0.5.8.2 (ad2a515b-4fce-4755-b206-65b178847e7d)
    Metadata Providers (3):
        ISAN Metadata Provider v0.9.1.2 (7e5acd92-c2dc-4503-a89f-8118feb8e796)
        TMDb v0.9.1.2 (5fbb0ac7-f2d8-4955-96eb-d820fa358c9a)
        ChapterDb v0.9.1.2 (5fce5c74-0498-4d8b-9aba-5ee6235ff469)
    Auto Detectors (1):
        BDHero Detective v0.9.1.2 (bda75b82-ab37-48b4-b830-1245399daa53)
    Name Providers (1):
        BDHero File Namer v0.9.1.2 (7841090c-8dae-4c54-87f8-958cbc6f8b0e)
    Muxers (1):
        FFmpeg v2.1.4.0 (beb49a31-0047-46cc-afce-455d026bb0cf)
    Post Processors (0)
2015-01-06 16:50:59,823 [ 1] INFO  BDHeroGUI.Components.DiscMenu - Scanning for discs...
2015-01-06 16:51:00,151 [ 1] INFO  BDHeroGUI.Components.DiscMenu - Found 1 discs
2015-01-06 16:51:03,084 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete -  - 00:00:00 elapsed, 00:00:00 remaining
2015-01-06 16:51:03,255 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2015-01-06 16:51:04,410 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning stream clip file 00000.CLPI - 00:00:01 elapsed, 00:00:00 remaining
2015-01-06 16:51:04,519 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 20.60 % complete - Scanning stream clip file 00033.CLPI - 00:00:01 elapsed, 00:00:00 remaining
2015-01-06 16:51:04,628 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 39.87 % complete - Scanning playlist file 00001.MPLS - 00:00:01 elapsed, 00:00:02 remaining
2015-01-06 16:51:04,628 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```

## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-05-05 02:27:45Z |  |
| 0 | ISAN Metadata Provider | 0.9.1.2 | 2014-05-05 02:27:44Z |  |
| 1 | TMDb | 0.9.1.2 | 2014-05-05 02:27:45Z |  |
| 2 | ChapterDb | 0.9.1.2 | 2014-05-05 02:27:45Z |  |
| 0 | BDHero Detective | 0.9.1.2 | 2014-05-05 02:27:43Z |  |
| 0 | BDHero File Namer | 0.9.1.2 | 2014-05-05 02:27:47Z |  |
| 0 | FFmpeg | 2.1.4.0 | 2014-05-05 02:27:52Z |  |

## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 2
    TotalPhysicalMemory: 8553357312 bytes (8.0 GiB)
    AvailableMemory: 6564110336 bytes (6.1 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: en-US
    CurrentCulture: en-US
    CurrentUICulture: en-US
```

**Comment by bdhero-issues** [comment]
BDHero GUI v0.9.1.2 portable (built on 2014-05-05 02:27:54Z)

## Stack Trace

```
BDHero.Plugin.DiscReader.Exceptions.PlaylistFileScanException: Error occurred while scanning playlist file 00001.MPLS ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at BDInfo.TSPlaylistFile.Scan(Dictionary`2 streamFiles, Dictionary`2 streamClipFiles) in [redacted]\TSPlaylistFile.cs:line 565
   at BDInfo.BDROM.Scan(CancellationToken cancellationToken) in [redacted]\BDROM.cs:line 352
   --- End of inner exception stack trace ---
   at BDHero.Plugin.DiscReader.DiscReader.BDROMOnPlaylistFileScanError(TSPlaylistFile playlistFile, Exception exception) in [redacted]\DiscReader.cs:line 122
   at BDInfo.BDROM.Scan(CancellationToken cancellationToken) in [redacted]\BDROM.cs:line 362
   at BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath) in [redacted]\DiscReader.cs:line 106
   at BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath) in [redacted]\DiscReader.cs:line 70
   at BDHero.Controller.<>c__DisplayClass2a.<ReadBDROM>b__27(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: DiscReaderPlugin
```

## Log Events

```
2015-03-01 10:25:09,478 [ 1] INFO  BDHero.Startup.LogInitializer - bdhero-gui v0.9.1.2 starting up
2015-03-01 10:25:09,597 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Checking if current process belongs to a Job Object...
2015-03-01 10:25:09,744 [ 1] DEBUG WindowsOSUtils.JobObjects.JobObjectManager - Current process does not belong to a Job Object.
2015-03-01 10:25:15,230 [ 1] INFO  BDHero.Startup.LogInitializer - Directories:
    IsPortable        = True
    RootDir           = [redacted]\bdhero-0.9.1.2
    InstallDir        = .
    AppConfigDir      = \Config\Application
    PluginConfigDir   = \Config\Plugins
    RequiredPluginDir = \Plugins\Required
    CustomPluginDir   = \Plugins\Custom
    LogDir            = \Logs
2015-03-01 10:25:15,540 [ 1] INFO  BDHero.Startup.PluginLoader - Loaded 7 plugins:
    Disc Readers (1):
        BDInfo Disc Reader v0.5.8.2 (ad2a515b-4fce-4755-b206-65b178847e7d)
    Metadata Providers (3):
        ISAN Metadata Provider v0.9.1.2 (7e5acd92-c2dc-4503-a89f-8118feb8e796)
        TMDb v0.9.1.2 (5fbb0ac7-f2d8-4955-96eb-d820fa358c9a)
        ChapterDb v0.9.1.2 (5fce5c74-0498-4d8b-9aba-5ee6235ff469)
    Auto Detectors (1):
        BDHero Detective v0.9.1.2 (bda75b82-ab37-48b4-b830-1245399daa53)
    Name Providers (1):
        BDHero File Namer v0.9.1.2 (7841090c-8dae-4c54-87f8-958cbc6f8b0e)
    Muxers (1):
        FFmpeg v2.1.4.0 (beb49a31-0047-46cc-afce-455d026bb0cf)
    Post Processors (0)
2015-03-01 10:25:15,648 [ 1] INFO  BDHeroGUI.Components.DiscMenu - Scanning for discs...
2015-03-01 10:25:19,033 [ 1] INFO  BDHeroGUI.Components.DiscMenu - Found 1 discs
2015-03-01 10:25:41,883 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete -  - 00:00:00 elapsed, 00:00:00 remaining
2015-03-01 10:25:41,913 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2015-03-01 10:25:45,024 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 17.94 % complete - Scanning stream clip file 00030.CLPI - 00:00:03 elapsed, 00:00:00 remaining
2015-03-01 10:25:45,130 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 28.57 % complete - Scanning stream clip file 00049.CLPI - 00:00:03 elapsed, 00:00:00 remaining
2015-03-01 10:25:45,234 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 38.54 % complete - Scanning stream clip file 00064.CLPI - 00:00:03 elapsed, 00:00:06 remaining
2015-03-01 10:25:45,391 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 39.87 % complete - Scanning playlist file 00001.MPLS - 00:00:03 elapsed, 00:00:05 remaining
2015-03-01 10:25:45,394 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```

## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-05-05 02:27:45Z |  |
| 0 | ISAN Metadata Provider | 0.9.1.2 | 2014-05-05 02:27:44Z |  |
| 1 | TMDb | 0.9.1.2 | 2014-05-05 02:27:45Z |  |
| 2 | ChapterDb | 0.9.1.2 | 2014-05-05 02:27:45Z |  |
| 0 | BDHero Detective | 0.9.1.2 | 2014-05-05 02:27:43Z |  |
| 0 | BDHero File Namer | 0.9.1.2 | 2014-05-05 02:27:47Z |  |
| 0 | FFmpeg | 2.1.4.0 | 2014-05-05 02:27:52Z |  |

## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 1
    TotalPhysicalMemory: 8016486400 bytes (7.5 GiB)
    AvailableMemory: 5896396800 bytes (5.5 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: en-US
    CurrentCulture: en-US
    CurrentUICulture: en-US
```
